
_kubectl_whoami()
{
    last_command="kubectl_whoami"

    command_aliases=()

    commands=()

    flags=()
    two_word_flags=()
    local_nonpersistent_flags=()
    flags_with_completion=()
    flags_completion=()

    # flags+=("--all")
    # local_nonpersistent_flags+=("--all")
    # flags+=("--allow-missing-template-keys")
    # local_nonpersistent_flags+=("--allow-missing-template-keys")
    # flags+=("--dry-run")
    # local_nonpersistent_flags+=("--dry-run")
    # flags+=("--field-selector=")
    # two_word_flags+=("--field-selector")
    # local_nonpersistent_flags+=("--field-selector=")
    # flags+=("--filename=")
    # two_word_flags+=("--filename")
    # flags_with_completion+=("--filename")
    # flags_completion+=("__kubectl_handle_filename_extension_flag json|yaml|yml")
    # two_word_flags+=("-f")
    # flags_with_completion+=("-f")
    # flags_completion+=("__kubectl_handle_filename_extension_flag json|yaml|yml")
    # local_nonpersistent_flags+=("--filename=")
    # flags+=("--kustomize=")
    # two_word_flags+=("--kustomize")
    # two_word_flags+=("-k")
    # local_nonpersistent_flags+=("--kustomize=")
    # flags+=("--local")
    # local_nonpersistent_flags+=("--local")
    # flags+=("--output=")
    # two_word_flags+=("--output")
    # two_word_flags+=("-o")
    # local_nonpersistent_flags+=("--output=")
    # flags+=("--overwrite")
    # local_nonpersistent_flags+=("--overwrite")
    # flags+=("--record")
    # local_nonpersistent_flags+=("--record")
    # flags+=("--recursive")
    # flags+=("-R")
    # local_nonpersistent_flags+=("--recursive")
    # flags+=("--resource-version=")
    # two_word_flags+=("--resource-version")
    # local_nonpersistent_flags+=("--resource-version=")
    # flags+=("--selector=")
    # two_word_flags+=("--selector")
    # two_word_flags+=("-l")
    # local_nonpersistent_flags+=("--selector=")
    # flags+=("--template=")
    # two_word_flags+=("--template")
    # flags_with_completion+=("--template")
    # flags_completion+=("_filedir")
    # local_nonpersistent_flags+=("--template=")
    # flags+=("--add-dir-header")
    # flags+=("--alsologtostderr")
    # flags+=("--as=")
    # two_word_flags+=("--as")
    # flags+=("--as-group=")
    # two_word_flags+=("--as-group")
    # flags+=("--cache-dir=")
    # two_word_flags+=("--cache-dir")
    # flags+=("--certificate-authority=")
    # two_word_flags+=("--certificate-authority")
    # flags+=("--client-certificate=")
    # two_word_flags+=("--client-certificate")
    # flags+=("--client-key=")
    # two_word_flags+=("--client-key")
    # flags+=("--cluster=")
    # two_word_flags+=("--cluster")
    # flags_with_completion+=("--cluster")
    # flags_completion+=("__kubectl_config_get_clusters")
    # flags+=("--context=")
    # two_word_flags+=("--context")
    # flags_with_completion+=("--context")
    # flags_completion+=("__kubectl_config_get_contexts")
    # flags+=("--insecure-skip-tls-verify")
    # flags+=("--kubeconfig=")
    # two_word_flags+=("--kubeconfig")
    # flags+=("--log-backtrace-at=")
    # two_word_flags+=("--log-backtrace-at")
    # flags+=("--log-dir=")
    # two_word_flags+=("--log-dir")
    # flags+=("--log-file=")
    # two_word_flags+=("--log-file")
    # flags+=("--log-file-max-size=")
    # two_word_flags+=("--log-file-max-size")
    # flags+=("--log-flush-frequency=")
    # two_word_flags+=("--log-flush-frequency")
    # flags+=("--logtostderr")
    # flags+=("--match-server-version")
    # flags+=("--namespace=")
    # two_word_flags+=("--namespace")
    # flags_with_completion+=("--namespace")
    # flags_completion+=("__kubectl_get_resource_namespace")
    # two_word_flags+=("-n")
    # flags_with_completion+=("-n")
    # flags_completion+=("__kubectl_get_resource_namespace")
    # flags+=("--password=")
    # two_word_flags+=("--password")
    # flags+=("--profile=")
    # two_word_flags+=("--profile")
    # flags+=("--profile-output=")
    # two_word_flags+=("--profile-output")
    # flags+=("--request-timeout=")
    # two_word_flags+=("--request-timeout")
    # flags+=("--server=")
    # two_word_flags+=("--server")
    # two_word_flags+=("-s")
    # flags+=("--skip-headers")
    # flags+=("--skip-log-headers")
    # flags+=("--stderrthreshold=")
    # two_word_flags+=("--stderrthreshold")
    # flags+=("--token=")
    # two_word_flags+=("--token")
    # flags+=("--user=")
    # two_word_flags+=("--user")
    # flags_with_completion+=("--user")
    # flags_completion+=("__kubectl_config_get_users")
    # flags+=("--username=")
    # two_word_flags+=("--username")
    # flags+=("--v=")
    # two_word_flags+=("--v")
    # two_word_flags+=("-v")
    # flags+=("--vmodule=")
    # two_word_flags+=("--vmodule")

    must_have_one_flag=()
    must_have_one_noun=()
    noun_aliases=()
}
